<a href="https://colab.research.google.com/github/Thabetiphanipriyagoud/NLP/blob/main/nlp%20assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



QUESTION 1   
 word2vec 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from gensim.models import KeyedVectors
import gensim

In [5]:
path = '/content/drive/MyDrive/GoogleNews-vectors-negative300.bin.gz'
model = KeyedVectors.load_word2vec_format(path, binary=True)

In [6]:
response_new=gensim.utils.simple_preprocess("A paragraph is a series sentences that are organized coherent are all related  a  single    pic Almost  every  piece writing  you  do  that is longer  than  a  few  sentences  should  be  organized  in    paragraphs This is because paragraphs show a reader where the subdivisions an essay begin end thus help the reader see the organization the essay grasp its main points Paragraphs  can  contain  many  different  kinds information  A paragraph could  contain  a  series  brief  examples  or  a  single  long illustration a general  point It  might  describe  a  place  character or  process narrate  a series events compare or contrast two or more things classify items in   categories  or  describe  causes     effects  Regardless       the  kind      information they contain all paragraphs share certain characteristics One     the most important     these is a   pic sentence")
response_new

['paragraph',
 'is',
 'series',
 'sentences',
 'that',
 'are',
 'organized',
 'coherent',
 'are',
 'all',
 'related',
 'single',
 'pic',
 'almost',
 'every',
 'piece',
 'writing',
 'you',
 'do',
 'that',
 'is',
 'longer',
 'than',
 'few',
 'sentences',
 'should',
 'be',
 'organized',
 'in',
 'paragraphs',
 'this',
 'is',
 'because',
 'paragraphs',
 'show',
 'reader',
 'where',
 'the',
 'subdivisions',
 'an',
 'essay',
 'begin',
 'end',
 'thus',
 'help',
 'the',
 'reader',
 'see',
 'the',
 'organization',
 'the',
 'essay',
 'grasp',
 'its',
 'main',
 'points',
 'paragraphs',
 'can',
 'contain',
 'many',
 'different',
 'kinds',
 'information',
 'paragraph',
 'could',
 'contain',
 'series',
 'brief',
 'examples',
 'or',
 'single',
 'long',
 'illustration',
 'general',
 'point',
 'it',
 'might',
 'describe',
 'place',
 'character',
 'or',
 'process',
 'narrate',
 'series',
 'events',
 'compare',
 'or',
 'contrast',
 'two',
 'or',
 'more',
 'things',
 'classify',
 'items',
 'in',
 'categori

In [8]:
model.wv[response_new]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


array([[ 0.01190186,  0.03808594,  0.21679688, ...,  0.05639648,
        -0.19140625, -0.03588867],
       [ 0.00704956, -0.07324219,  0.171875  , ...,  0.01123047,
         0.1640625 ,  0.10693359],
       [-0.12792969,  0.09326172, -0.02087402, ...,  0.02233887,
        -0.08154297, -0.15527344],
       ...,
       [ 0.00704956, -0.07324219,  0.171875  , ...,  0.01123047,
         0.1640625 ,  0.10693359],
       [ 0.00460815,  0.16308594, -0.17675781, ..., -0.38085938,
        -0.23046875,  0.15722656],
       [ 0.11767578, -0.234375  ,  0.4765625 , ..., -0.24511719,
         0.1484375 ,  0.07714844]], dtype=float32)

b. UES

In [9]:
import tensorflow_hub as hub
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
Sentences = ["A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.","  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs. "," This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points."," Paragraphs can  contain  many  different  kinds  of  information."," A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point. "," It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. ","Regardless of the kind of information they contain, all paragraphs share certain characteristics. ","One of the most important of these is a topic sentence."]

embeddings = embed(Sentences)
print(embeddings)
for i in range(len(Sentences)):
    print(Sentences[i])
    print(embeddings[i])

tf.Tensor(
[[ 0.01168496 -0.03060572  0.06116336 ... -0.08641755  0.0002505
   0.05482749]
 [ 0.02972507 -0.03655469  0.08002593 ... -0.07038905 -0.0283213
   0.04804676]
 [ 0.07221661 -0.04182237  0.05336686 ... -0.06942353  0.01795934
   0.06641504]
 ...
 [ 0.01586947 -0.05243036  0.0606509  ... -0.06435591  0.04215747
   0.06304204]
 [ 0.04141247  0.02588907 -0.0062563  ... -0.02162989  0.00910817
   0.03623575]
 [ 0.01578411 -0.02142678  0.00402448 ... -0.09605585 -0.06707881
   0.07970381]], shape=(8, 512), dtype=float32)
A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.
tf.Tensor(
[ 1.16849625e-02 -3.06057241e-02  6.11633621e-02  8.47723782e-02
 -5.83404116e-03  2.84162583e-03  2.59479079e-02  3.90261016e-03
 -5.55586144e-02  5.68111017e-02 -8.95012915e-03 -4.50471742e-03
 -6.06310219e-02  3.18566561e-02 -6.86047673e-02 -9.39451605e-02
 -4.23613675e-02  3.93056758e-02 -9.02280435e-02 -5.53663708e-02
 -1.92777591e-03 

c. ELMO

In [10]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()
elmo = hub.Module("https://tfhub.dev/google/elmo/3", trainable=True)
  
embeddings = elmo(
    ["A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.","  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs. "," This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points."," Paragraphs can  contain  many  different  kinds  of  information."," A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point. "," It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. ","Regardless of the kind of information they contain, all paragraphs share certain characteristics. ","One of the most important of these is a topic sentence."],
    signature="default",
    as_dict=True)["elmo"]
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
print(sess.run(embeddings))


Instructions for updating:
Use `tf.global_variables_initializer` instead.


[[[ 0.29287004 -0.14378013 -0.32574052 ... -0.39559263 -0.35758853
   -0.03588088]
  [-0.59441584  0.09640743  0.50537694 ...  0.22031914  0.269769
    0.46307266]
  [-0.1708326  -0.18744111 -0.27626696 ... -0.67550904  0.25389987
    0.6540271 ]
  ...
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]]

 [[ 0.3972119  -0.1509141   0.58700776 ... -0.44112715 -0.4109748
    0.15087722]
  [ 0.22274575 -0.12839264  0.01303142 ... -0.48178503 -0.6057211
    0.04756459]
  [-0.6277796  -0.454895    0.9650203  ... -0.6934171   0.2825519
    0.21852238]
  ...
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650

d. GPT2

In [11]:
!pip install -q gradio
!pip install -q git+https://github.com/huggingface/transformers.git

     |████████████████████████████████| 5.3 MB 5.2 MB/s 
     |████████████████████████████████| 2.3 MB 56.7 MB/s 
     |████████████████████████████████| 84 kB 3.4 MB/s 
     |████████████████████████████████| 112 kB 64.4 MB/s 
     |████████████████████████████████| 55 kB 3.3 MB/s 
     |████████████████████████████████| 270 kB 47.4 MB/s 
     |████████████████████████████████| 212 kB 59.4 MB/s 
     |████████████████████████████████| 84 kB 3.2 MB/s 
     |████████████████████████████████| 54 kB 3.0 MB/s 
     |████████████████████████████████| 57 kB 4.8 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 80 kB 7.7 MB/s 
     |████████████████████████████████| 68 kB 6.1 MB/s 
     |████████████████████████████████| 46 kB 3.6 MB/s 
     |████████████████████████████████| 856 kB 47.1 MB/s 
     |████████████████████████████████| 4.0 MB 43.1 MB/s 
     |████████████████████████████████| 593 kB 46.9 MB/s 
  Installing build dependencies .

In [12]:
import gradio as gr
import tensorflow as tf
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer

In [13]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model2 = TFGPT2LMHeadModel.from_pretrained("gpt2", pad_token_id= tokenizer.eos_token_id)

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/498M [00:00<?, ?B/s]

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'tfgpt2lm_head_model/transformer/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    summarize, message, name)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/check_ops.py", line 427, in _binary_assert
    return control_flow_ops.Assert(condition, data, summarize=summarize)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 1082, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/usr/local/lib/python3.7/dist-packages/te

In [14]:
sentences = ["A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.","  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs. "," This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points."," Paragraphs can  contain  many  different  kinds  of  information."," A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point. "," It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. ","Regardless of the kind of information they contain, all paragraphs share certain characteristics. ","One of the most important of these is a topic sentence."]
re = tokenizer.encode(sentences)
print(re)

[50256, 50256, 50256, 50256, 50256, 50256, 50256, 50256]


e. BERT

In [15]:
!pip install simpletransformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 250 kB 5.3 MB/s 
     |████████████████████████████████| 9.2 MB 50.4 MB/s 
     |████████████████████████████████| 1.9 MB 50.7 MB/s 
     |████████████████████████████████| 441 kB 38.4 MB/s 
     |████████████████████████████████| 1.3 MB 41.9 MB/s 
     |████████████████████████████████| 43 kB 2.0 MB/s 
     |████████████████████████████████| 182 kB 56.3 MB/s 
     |████████████████████████████████| 162 kB 68.1 MB/s 
     |████████████████████████████████| 63 kB 1.9 MB/s 
     |████████████████████████████████| 162 kB 65.1 MB/s 
     |████████████████████████████████| 158 kB 58.2 MB/s 
     |████████████████████████████████| 157 kB 62.8 MB/s 
     |████████████████████████████████| 157 kB 48.5 MB/s 
     |████████████████████████████████| 157 kB 67.4 MB/s 
     |████████████████████████████████| 157 kB 66.3 MB/s 
     |██████████████████████████████

In [16]:
from simpletransformers.language_representation import RepresentationModel

In [17]:
sentences = ["A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.",
             "  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs. ",
             " This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points.",
             " Paragraphs can  contain  many  different  kinds  of  information.",
             " A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point. ",
             " It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. ",
             "Regardless of the kind of information they contain, all paragraphs share certain characteristics. ",
             "One of the most important of these is a topic sentence."]
model = RepresentationModel(
    model_type='bert',
    model_name='bert-base-uncased',
    use_cuda=False
)
word_vectors = model.encode_sentences(sentences, combine_strategy=None)

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForTextRepresentation: ['cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertForTextRepresentation from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTextRepresentation from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

In [18]:
word_vectors.shape

(8, 40, 768)

In [19]:
word_vectors

array([[[-0.32188225, -0.09209722, -0.2929884 , ..., -0.25328925,
          0.10158574,  0.68979895],
        [-0.27313572,  0.17119956, -0.10808659, ..., -0.22688961,
          0.2374427 ,  0.12140085],
        [ 0.3880793 ,  0.02563908, -0.63863045, ...,  0.4560714 ,
          0.3077981 , -0.86568075],
        ...,
        [ 0.18976857, -0.05072101,  0.5242336 , ..., -0.10684858,
         -0.00271132, -0.04620938],
        [ 0.13916801,  0.03951407,  0.48373023, ..., -0.18287873,
         -0.0308386 ,  0.07986066],
        [ 0.12490664,  0.29766712,  0.3783258 , ..., -0.31597805,
         -0.06702995,  0.14396629]],

       [[ 0.06578048,  0.13254675, -0.35793442, ..., -0.18910325,
          0.05906608,  0.66571164],
        [ 0.5014778 ,  0.43959334,  0.46919477, ...,  0.0819297 ,
         -0.02224354,  0.53288424],
        [-0.60374874,  0.42920977,  0.53432685, ...,  0.07126594,
          0.3030653 ,  0.6760071 ],
        ...,
        [-0.01918198, -0.38057584,  0.05521787, ..., -

In [20]:
sentence_vectors = model.encode_sentences(sentences, combine_strategy="mean")
sentence_vectors.shape
sentence_vectors

array([[-0.21345517,  0.07659665,  0.15188614, ..., -0.06890777,
        -0.03783415,  0.1365811 ],
       [-0.02344349,  0.19011176,  0.04032319, ..., -0.07841675,
        -0.05492901,  0.16003636],
       [-0.41222858,  0.18103825,  0.02429553, ..., -0.01586459,
         0.01885071,  0.20555632],
       ...,
       [ 0.1224546 ,  0.23142219, -0.1993598 , ..., -0.12404256,
        -0.36017174,  0.30762663],
       [ 0.28345555,  0.3366952 ,  0.06869622, ..., -0.21586725,
        -0.04929547,  0.14809199],
       [-0.13691476, -0.2106152 , -0.04117552, ...,  0.0209422 ,
         0.05759983, -0.16207817]], dtype=float32)

QUESTION 2 - named entities

In [21]:
import spacy


In [22]:
nlp = spacy.load("en_core_web_sm")

In [23]:
doc = nlp("A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs.  This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points. Paragraphs can  contain  many  different  kinds  of  information. A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point.  It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. Regardless of the kind of information they contain, all paragraphs share certain characteristics. One of the most important of these is a topic sentence.")


In [24]:
for ent in doc.ents:
  print(ent.text, ent.start_char, ent.end_char, ent.label_)

two 708 711 CARDINAL
One 895 898 CARDINAL


QUESTION 3 - similar sentences

In [25]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 3.0 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=b30ef18d89f991d42664f9baa67ad4cb8cc037068771bbe062c8431e0c248809
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [26]:
sentences = ["A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.",
             "  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs. ",
             " This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points.",
             " Paragraphs can  contain  many  different  kinds  of  information.",
             " A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point. ",
             " It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. ",
             "Regardless of the kind of information they contain, all paragraphs share certain characteristics. ",
             "One of the most important of these is a topic sentence."]


In [27]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-distilroberta-v1')

Downloading:   0%|          | 0.00/737 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/653 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/15.7k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/329M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/333 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/798k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [28]:
sentence_embeddings = model.encode(sentences)
sentence_embeddings.shape
sentence_embeddings

array([[ 0.00965958, -0.00293273,  0.01081129, ..., -0.01149384,
        -0.00271008,  0.01476445],
       [-0.01768139,  0.02993892,  0.0079164 , ..., -0.01688201,
         0.01722328,  0.05301636],
       [ 0.00147376, -0.01587111,  0.00515314, ..., -0.01379193,
         0.02069645,  0.05720283],
       ...,
       [-0.05971985, -0.03836311,  0.00221552, ..., -0.00496627,
         0.0083272 , -0.04168425],
       [ 0.01119403,  0.00083715,  0.00956389, ..., -0.01116421,
        -0.01548793,  0.04113044],
       [ 0.04353701, -0.00512412,  0.00020998, ...,  0.0239433 ,
        -0.0204486 ,  0.03564684]], dtype=float32)

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)

array([[0.6945995 , 0.6793491 , 0.7508341 , 0.72967523, 0.33892256,
        0.62682295, 0.46804008]], dtype=float32)

In [31]:
similarity_score = cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
).flatten()

In [32]:
import pandas as pd
pd.DataFrame({"sentence":sentences[1:],"similarity_score":similarity_score})

sentence  similarity_score
0    Almost  every  piece  of  writing you  do  t...          0.694600
1   This  is because paragraphs show a reader whe...          0.679349
2   Paragraphs can  contain  many  different  kin...          0.750834
3   A paragraph could  contain  a  series  of  br...          0.729675
4   It  might  describe  a  place,  character,  o...          0.338923
5  Regardless of the kind of information they con...          0.626823
6  One of the most important of these is a topic ...          0.468040

QUESTION 4 - parts of speech


In [33]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [34]:
text = "A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs.  This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points. Paragraphs can  contain  many  different  kinds  of  information. A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point.  It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. Regardless of the kind of information they contain, all paragraphs share certain characteristics. One of the most important of these is a topic sentence."
result = word_tokenize(text)

In [35]:
# print(result)
pos = nltk.pos_tag(result)
print(pos)

[('A', 'DT'), ('paragraph', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('series', 'NN'), ('of', 'IN'), ('sentences', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('organized', 'VBN'), ('and', 'CC'), ('coherent', 'NN'), (',', ','), ('and', 'CC'), ('are', 'VBP'), ('all', 'DT'), ('related', 'VBN'), ('to', 'TO'), ('a', 'DT'), ('single', 'JJ'), ('topic', 'NN'), ('.', '.'), ('Almost', 'CC'), ('every', 'DT'), ('piece', 'NN'), ('of', 'IN'), ('writing', 'VBG'), ('you', 'PRP'), ('do', 'VBP'), ('that', 'DT'), ('is', 'VBZ'), ('longer', 'JJR'), ('than', 'IN'), ('a', 'DT'), ('few', 'JJ'), ('sentences', 'NNS'), ('should', 'MD'), ('be', 'VB'), ('organized', 'VBN'), ('into', 'IN'), ('paragraphs', 'NN'), ('.', '.'), ('This', 'DT'), ('is', 'VBZ'), ('because', 'IN'), ('paragraphs', 'NN'), ('show', 'VBP'), ('a', 'DT'), ('reader', 'NN'), ('where', 'WRB'), ('the', 'DT'), ('subdivisions', 'NNS'), ('of', 'IN'), ('an', 'DT'), ('essay', 'NN'), ('begin', 'NN'), ('and', 'CC'), ('end', 'NN'), (',', ','), ('and', 'CC'), ('thus'